language: ruby

os:
  - linux
  - osx

rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.6
  - jruby-9.2.6.0

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9.2.6.0

notifications:
  email: false

env:
  global:
    - JRUBY_OPTS="--debug"
    - NO_IPV6_TESTS=1

script:
  - bundle exec rake build
  - bundle exec rake coveralls
